basePath: /
consumes:
- application/json
definitions:
  Dto:
    properties:
      fullName:
        type: string
        x-go-name: FullName
      id:
        $ref: '#/definitions/UUID'
    type: object
    x-go-package: github.com/turnkeyca/monolith/user
  GenericError:
    properties:
      message:
        type: string
        x-go-name: Message
    type: object
    x-go-package: github.com/turnkeyca/monolith/user
  UUID:
    description: |-
      A UUID is a 128 bit (16 byte) Universal Unique IDentifier as defined in RFC
      4122.
    items:
      format: uint8
      type: integer
    type: array
    x-go-package: github.com/google/uuid
  ValidationError:
    properties:
      messages:
        items:
          type: string
        type: array
        x-go-name: Messages
    type: object
    x-go-package: github.com/turnkeyca/monolith/user
info:
  description: Documentation for Turnkey API
  title: of Turnkey API
  version: 1.0.0
paths:
  /api/short-url?longUrl={url}:
    get:
      description: get a bitly short url
      operationId: getShortUrl
      tags:
      - shorturl
  /api/user:
    post:
      description: create a new user
      operationId: createUser
      responses:
        "200":
          $ref: '#/responses/userResponse'
        "422":
          $ref: '#/responses/userErrorValidation'
        "500":
          $ref: '#/responses/userErrorResponse'
      tags:
      - user
    put:
      description: update a user
      operationId: updateUser
      parameters:
      - $ref: '#/definitions/UUID'
        description: The id of the user for which the operation relates
        in: path
        name: id
        required: true
        x-go-name: Id
      responses:
        "201":
          $ref: '#/responses/noContentResponse'
        "404":
          $ref: '#/responses/userErrorResponse'
        "422":
          $ref: '#/responses/userErrorValidation'
      tags:
      - user
  /api/user/{id}:
    delete:
      description: delete a user
      operationId: deleteUser
      parameters:
      - $ref: '#/definitions/UUID'
        description: The id of the user for which the operation relates
        in: path
        name: id
        required: true
        x-go-name: Id
      responses:
        "201":
          $ref: '#/responses/noContentResponse'
        "404":
          $ref: '#/responses/userErrorResponse'
        "500":
          $ref: '#/responses/userErrorResponse'
      tags:
      - user
    get:
      description: return a user
      operationId: getUser
      parameters:
      - $ref: '#/definitions/UUID'
        description: The id of the user for which the operation relates
        in: path
        name: id
        required: true
        x-go-name: Id
      responses:
        "200":
          $ref: '#/responses/userResponse'
        "404":
          $ref: '#/responses/userErrorResponse'
      tags:
      - user
produces:
- application/json
responses:
  noContentResponse:
    description: No content is returned by this API endpoint
  shortUrlErrorResponse:
    description: Generic error message returned as a string
    schema:
      $ref: '#/definitions/GenericError'
  shortUrlResponse:
    description: A short url
    schema:
      $ref: '#/definitions/Dto'
  userErrorResponse:
    description: Generic error message returned as a string
    schema:
      $ref: '#/definitions/GenericError'
  userErrorValidation:
    description: Validation errors defined as an array of strings
    schema:
      $ref: '#/definitions/ValidationError'
  userResponse:
    description: A user
    schema:
      $ref: '#/definitions/Dto'
schemes:
- http
swagger: "2.0"
